import { useState, useEffect } from "react"
import Head from 'next/head'

import { getTrending } from "services/api"

import ListItem from "components/list_item"
import Playing from "components/playing";

export default function Home() {
  const [trending, setTrending] = useState<VideoItem[]>([]);

  useEffect(() => {
    getTrending().then(setTrending)
  }, [])

  return (
    <div className="h-screen overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul className="overflow-auto h-full">
        {trending.map((item) => (
          <ListItem item={item} key={item.videoId} />
        ))}
      </ul>

      <Playing />
    </div >
  )
}
